flush: 5
logLevel: info
env:
  - name: HOST_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: READ_FROM_HEAD
    value: "Off"
  - name: READ_FROM_TAIL
    value: "On"
envWithTpl:
  - name: AWS_REGION
    value: "{{ .Values.aws_region }}"
  - name: CLUSTER_NAME
    value: "{{ .Values.eks_cluster_name }}"
config:
  fluent-bit.conf: |
    [SERVICE]
        Flush                      5
        Log_Level                  info
        Daemon                     off
        Parsers_File               parsers.conf
        HTTP_Server                ${HTTP_SERVER}
        HTTP_Listen                0.0.0.0
        HTTP_Port                  ${HTTP_PORT}
        storage.path               /var/fluent-bit/state/flb-storage/
        storage.sync               normal
        storage.checksum           off
        storage.backlog.mem_limit  5M
        
    @INCLUDE application-log.conf
    @INCLUDE dataplane-log.conf
    @INCLUDE host-log.conf

  application-log.conf: |
    [INPUT]
        Name                        tail
        Tag                         kube.<namespace_name>.<pod_name>.<container_name>
        Tag_Regex                   (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        Path                        /var/log/containers/*.log
        Exclude_Path                /var/log/containers/aws-load-balancer-controller*, /var/log/containers/cluster-autoscaler*, /var/log/containers/metric-server*, /var/log/containers/node-driver-registrar*, /var/log/containers/secret-store*, /var/log/containers/provider-aws-installer*, /var/log/containers/cloudwatch-agent*, /var/log/containers/fluent-bit*, /var/log/containers/aws-node*, /var/log/containers/kube-proxy*, /var/log/containers/notification-controller*, /var/log/containers/kustomize-controller*, /var/log/containers/source-controller*
        Parser                      docker
        DB                          /var/fluent-bit/state/flb_container.db
        Mem_Buf_Limit               5MB
        Skip_Long_Lines             On
        Refresh_Interval            10
        Rotate_Wait                 30

    [INPUT]
        Name                        tail
        Tag                         application.*
        Exclude_Path                /var/log/containers/cloudwatch-agent*, /var/log/containers/fluent-bit*, /var/log/containers/aws-node*, /var/log/containers/kube-proxy*, /var/log/containers/notification-controller*, /var/log/containers/kustomize-controller*, /var/log/containers/source-controller*
        Path                        /var/log/containers/*.log
        Docker_Mode                 On
        Docker_Mode_Flush           5
        Docker_Mode_Parser          container_firstline
        Parser                      docker
        DB                          /var/fluent-bit/state/flb_container.db
        Mem_Buf_Limit               50MB
        Skip_Long_Lines             On
        Refresh_Interval            10
        Rotate_Wait                 30
        storage.type                filesystem
        Read_from_Head              ${READ_FROM_HEAD}

    [INPUT]
        Name                        tail
        Tag                         application.*
        Path                        /var/log/containers/fluent-bit*
        Parser                      docker
        DB                          /var/fluent-bit/state/flb_log.db
        Mem_Buf_Limit               5MB
        Skip_Long_Lines             On
        Refresh_Interval            10
        Read_from_Head              ${READ_FROM_HEAD}

    [INPUT]
        Name                        tail
        Tag                         application.*
        Path                        /var/log/containers/cloudwatch-agent*
        Docker_Mode                 On
        Docker_Mode_Flush           5
        Docker_Mode_Parser          cwagent_firstline
        Parser                      docker
        DB                          /var/fluent-bit/state/flb_cwagent.db
        Mem_Buf_Limit               5MB
        Skip_Long_Lines             On
        Refresh_Interval            10
        Read_from_Head              ${READ_FROM_HEAD}

    [FILTER]
        Name                        kubernetes
        Match                       application.*
        Kube_URL                    https://kubernetes.default.svc:443
        Kube_Tag_Prefix             application.var.log.containers.
        Merge_Log                   On
        Merge_Log_Key               log_processed
        K8S-Logging.Parser          On
        K8S-Logging.Exclude         Off
        Labels                      Off
        Annotations                 Off
        Use_Kubelet                 On
        Kubelet_Port                10250
        Buffer_Size                 0

    [FILTER]
        Name                        modify
        Match                       application.*
        # Replace (ask splunk team)
        Set index                   app_talentjs_cloud
        Set source                  k8s_container
        # Replace (ask splunk team) 
        Set sourcetype              talentjs 

    [OUTPUT]
        Name                        splunk
        Match                       application.*
        Host                        splunk-nlb-nlb-03ea3e69c8a5908f.elb.ap-southeast-3.amazonaws.com
        Port                        8088
        # Replace (ask splunk team)
        Splunk_Token                6b1fb2ec-b33c-4e39-9d23-904fff86ebdb
        Splunk_Send_Raw             On
        TLS                         On
        TLS.Verify                  Off
        net.connect_timeout         30
        net.keepalive               On
        net.keepalive_idle_timeout  10
        net.keepalive_max_recycle   5
        http_buffer_size            5M

  application-log.conf: |
    [INPUT]
        Name                tail
        Tag                 host.dmesg
        Path                /var/log/dmesg
        Parser              syslog
        DB                  /var/fluent-bit/state/flb_dmesg.db
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Read_from_Head      ${READ_FROM_HEAD}

    [INPUT]
        Name                tail
        Tag                 host.messages
        Path                /var/log/messages
        Parser              syslog
        DB                  /var/fluent-bit/state/flb_messages.db
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Read_from_Head      ${READ_FROM_HEAD}

    [INPUT]
        Name                tail
        Tag                 host.secure
        Path                /var/log/secure
        Parser              syslog
        DB                  /var/fluent-bit/state/flb_secure.db
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Read_from_Head      ${READ_FROM_HEAD}

    [FILTER]
        Name                aws
        Match               host.*
        imds_version        v2

  parsers.conf: |
    [PARSER]
        Name         docker
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L
        Time_Keep    On
        # Command       |  Decoder  | Field | Optional Action   |
        # ==============|===========|=======|===================|
        Decode_Field_As    escaped     log

    [PARSER]
        Name                syslog
        Format              regex
        Regex               ^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key            time
        Time_Format         %b %d %H:%M:%S

    [PARSER]
        Name                container_firstline
        Format              regex
        Regex               (?<log>(?<="log":")\S(?!\.).*?)(?<!\\)".*(?<stream>(?<="stream":").*?)".*(?<time>\d{4}-\d{1,2}-\d{1,2}T\d{2}:\d{2}:\d{2}\.\w*).*(?=})
        Time_Key            time
        Time_Format         %Y-%m-%dT%H:%M:%S.%LZ

    [PARSER]
        Name                cwagent_firstline
        Format              regex
        Regex               (?<log>(?<="log":")\d{4}[\/-]\d{1,2}[\/-]\d{1,2}[ T]\d{2}:\d{2}:\d{2}(?!\.).*?)(?<!\\)".*(?<stream>(?<="stream":").*?)".*(?<time>\d{4}-\d{1,2}-\d{1,2}T\d{2}:\d{2}:\d{2}\.\w*).*(?=})
        Time_Key            time
        Time_Format         %Y-%m-%dT%H:%M:%S.%LZ